config/routes.rb
Rails.application.routes.draw do
  resources :posts
  # Authentication
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [:index, :show, :destroy]
  resource  :password, only: [:edit, :update]
  namespace :identity do
    resource :email,              only: [:edit, :update]
    resource :email_verification, only: [:show, :create]
    resource :password_reset,     only: [:new, :edit, :create, :update]
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "projects#index"

  # Clients
  resources :clients

  # Comments
  resources :comments, only: [:create, :destroy]

  # Documents
  resources :documents

  # Invoices
  resources :invoices

  # Projects
  resources :projects do
    # Invoice
    resources :invoices

    # Spaces
    get "spaces/bulk_new", to: "project_spaces#bulk_new"
    post "spaces/bulk_create", to: "project_spaces#bulk_create"
    resources :spaces, controller: "project_spaces" do
      post :duplicate
      resources :items, controller: "project_items"
    end

    # Quotes
    resources :quotes
  end

  # Project Items
  resources :project_items, only: [:create, :destroy, :update] do
    post :duplicate
  end

  # Quotes
  resources :quotes

  # Users
  resources :users
end

app/models/project_space.rb
class ProjectSpace < ApplicationRecord
  belongs_to :project

  has_many :project_items
  has_many_attached :images do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
  end
end

class ProjectSpaceCloner < Clowne::Cloner
  include_association :project_items

  trait :append_copy do
    finalize do |source, record, params|
      record.title = "#{source.title} Copy"
    end
  end
end

app/controllers/project_spaces_controller.rb
class ProjectSpacesController < ApplicationController
  before_action :set_project_space, only: %i[ show edit update destroy ]

  # GET /project_spaces or /project_spaces.json
  def index
    @project_spaces = policy_scope(ProjectSpace)
      .where(project_id: params[:project_id])
  end

  # GET /project_spaces/1 or /project_spaces/1.json
  def show
    @categories = Category.where(category_type: "ProjectItem")
  end

  # GET /project_spaces/new
  def new
    @project_space = ProjectSpace.new(project_id: params[:project_id])
    @projects = policy_scope(Project)
      .select("sub_projects.*")
      .joins_sub_projects
      .includes(:parent_project)
      .order("projects.title ASC, sub_projects.title ASC")
  end

  # GET /project_spaces/bulk_new
  def bulk_new
    @project_space = ProjectSpace.new
  end

  # GET /project_spaces/1/edit
  def edit
    @projects = policy_scope(Project)
      .select("sub_projects.*")
      .joins_sub_projects
      .includes(:parent_project)
      .order("projects.title ASC, sub_projects.title ASC")
  end

  # POST /project_spaces or /project_spaces.json
  def create
    @project_space = ProjectSpace.new(project_space_params)
    @project_space.project_id = params[:project_id]

    respond_to do |format|
      if @project_space.save
        format.html { redirect_to project_space_url(@project_space, @project_space), notice: "Project space was successfully created." }
        format.json { render :show, status: :created, location: @project_space }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project_space.errors, status: :unprocessable_entity }
      end
    end
  end

  def bulk_create
    project_space_titles = params.dig(:project_space, :titles).reject { |t| t.empty? }
    
    project_space_titles.each do |title|
      ProjectSpace.create!(title: title, project_id: params[:project_id])
    end

    respond_to do |format|
      format.html { redirect_to project_url(params[:project_id]), notice: "Project spaces were successfully created." }
    end
  end

  # PATCH/PUT /project_spaces/1 or /project_spaces/1.json
  def update
    respond_to do |format|
      if @project_space.update(project_space_params)
        format.html { redirect_to project_space_url(@project_space, @project_space), notice: "Project space was successfully updated." }
        format.json { render :show, status: :ok, location: @project_space }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project_space.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /project_spaces/1/duplicate or /project_spaces/1/duplicate.json
  def duplicate
    @original_space = ProjectSpace.find(params[:space_id])
    @project_space = ProjectSpaceCloner.call(@original_space, traits: :append_copy).to_record

    respond_to do |format|
      if @project_space.save
        format.html { redirect_to project_space_url(@project_space.project_id, @project_space.id), notice: "Project item was successfully created." }
        format.json { render :show, status: :created, location: @project_space }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project_space.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_spaces/1 or /project_spaces/1.json
  def destroy
    @project_space.destroy!

    respond_to do |format|
      format.html { redirect_to project_url(@project_space.project_id), notice: "Project space was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project_space
      @project_space = ProjectSpace.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_space_params
      params.fetch(:project_space, {})
        .permit(
          :title,
          images: [],
        )
    end
end

app/helpers/project_spaces_helper.rb
module ProjectSpacesHelper
end

app/views/project_spaces/_bulk_form.html.erb
<%= form_with(url: project_spaces_bulk_create_path, class: "w-full") do |form| %>
  <% if project_space.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project_space.errors.count, "error") %> prohibited this project_space from being saved:</h2>

      <ul>
        <% project_space.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% 10.times do |i| %>
  <div class="flex flex-wrap -mx-3 mb-2">
    <div class="w-full px-3">
      <%= form.label "Space ##{i + 1}", class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
      <input name="project_space[titles][]" type="text" class="appearance-none block w-full bg-gray-50 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" />
    </div>
  </div>
  <% end %>

  <div class="flex justify-end">
    <%= link_to "Go Back", project_path(params[:project_id]), class: "cursor-pointer inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border text-primary h-10 px-4 py-2 mr-2" %>
    <%= form.submit class: "cursor-pointer inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground hover:bg-primary/90 h-10 px-4 py-2" %>
  </div>
<% end %>

app/views/project_spaces/_category_group.html.erb
<h4 class="text-xl font-semibold leading-none tracking-tight mt-8">
  <%= category.title %>
</h4>

<% project_space.project_items.where(category: category).each do |project_item| %>
<%= render partial: "project_items/project_item", locals: { project_item: project_item } %>
<% end %>

<div class="rounded-lg border bg-white text-card-foreground shadow-sm mt-4">
  <div class="space-y-1.5 p-6 flex flex-col items-end gap-4">
    <a
      class="w-full md:w-auto inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground hover:bg-primary/90 h-10 px-4 py-2"
      href="<%= new_project_space_item_path(project_space.project, project_space, category_id: category.id) %>"
    >
      Add to <%= category.title %>
    </a>
  </div>
</div>

app/views/project_spaces/_form.html.erb
<%= form_with(model: project_space, class: "w-full") do |form| %>
  <% if project_space.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project_space.errors.count, "error") %> prohibited this project_space from being saved:</h2>

      <ul>
        <% project_space.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex flex-wrap -mx-3 mb-2">
    <div class="w-full px-3">
      <%= form.label "Project", class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
      <%= form.select(
        :project_id,
        projects.map { |project| ["#{project.parent_project&.title} - #{project.title}", project.id] },
        { include_blank: "Please Select..." },
        { class: "appearance-none block w-full bg-gray-50 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" }
      ) %>
    </div>
  </div>

  <div class="flex flex-wrap -mx-3 mb-2">
    <div class="w-full px-3">
      <%= form.label "Title", class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
      <%= form.text_field :title, class: "appearance-none block w-full bg-gray-50 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" %>
    </div>
  </div>

  <div class="flex flex-wrap -mx-3 mb-2">
    <div class="w-full px-3">
      <%= form.label "Inspiration Images", class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
      <%= form.file_field :images, multiple: true, class: "appearance-none block w-full bg-gray-50 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" %>
    </div>
  </div>

  <div class="flex justify-end">
    <% project_space.images.each do |image| %>
      <%= form.hidden_field :images, multiple: true, value: image.signed_id %>
    <% end %>

    <% if project_space.new_record? %>
    <%= link_to "Go Back", project_path(params[:project_id]), class: "cursor-pointer inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border text-primary h-10 px-4 py-2 mr-2" %>
    <% else %>
    <%= link_to "Go Back", project_space_path(project_space.project_id, project_space.id), class: "cursor-pointer inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border text-primary h-10 px-4 py-2 mr-2" %>
    <% end %>
    
    <%= form.submit class: "cursor-pointer inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground hover:bg-primary/90 h-10 px-4 py-2" %>
  </div>
<% end %>

app/views/project_spaces/_project_space.html.erb
<div id="<%= dom_id project_space %>" class="rounded-lg border bg-white text-card-foreground shadow-sm">
  <div class="p-6 flex flex-col gap-2 md:gap-0 md:flex-row md:items-center justify-between">
    <div class="grid gap-1">
      <h3 class="text-2xl font-semibold leading-none tracking-tight">
        <%= link_to project_space.title, project_space.project %>
      </h3>
      
      <h4>
        <%= link_to "#{project_space.project.parent_project.title}", project_space.project.parent_project %> 
        <span> > </span>
        <%= link_to "#{project_space.project.title}", project_space.project %>
      </h4>
    </div>

    <div class="flex gap-2">
      <%= link_to("Edit", edit_project_space_path(project_space.project_id, project_space), class: "inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 text-primary border hover:border-gray-300 h-7 px-2 py-1") %>
      <%= button_to("Duplicate", project_space_duplicate_path(project_space.project_id, space_id: project_space.id), method: :post, class: "inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 text-primary border hover:border-gray-300 h-7 px-2 py-1") %>
      <%= button_to("Delete", project_space_path(project_space.project_id, project_space.id), method: :delete, data: { turbo_confirm: 'Are you sure?', turbo_method: :delete }, class: "inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 text-primary border hover:border-gray-300 h-7 px-2 py-1") %>
    </div>
  </div>
</div>

app/views/project_spaces/bulk_new.html.erb
<div class="flex flex-col">
  <div class="rounded-lg border bg-white text-card-foreground shadow-sm">
    <div class="space-y-1.5 p-6 flex flex-row items-center gap-4">
      <div class="grid gap-1">
        <h3 class="text-2xl font-semibold leading-none tracking-tight">
          Bulk Create Spaces
        </h3>
      </div>
    </div>
  </div>

  <div class="rounded-lg border bg-white text-card-foreground shadow-sm mt-4">
    <div class="space-y-1.5 p-6 flex flex-row items-center gap-4">
      <%= render "bulk_form", project_space: @project_space %>
    </div>
  </div>
</div>

app/views/project_spaces/edit.html.erb
<div class="flex flex-col">
  <div class="rounded-lg border bg-white text-card-foreground shadow-sm">
    <div class="space-y-1.5 p-6 flex flex-row items-center gap-4">
      <div class="grid gap-1">
        <h3 class="text-2xl font-semibold leading-none tracking-tight">
          Edit Project Space
        </h3>
      </div>
    </div>
  </div>

  <div class="rounded-lg border bg-white text-card-foreground shadow-sm mt-4">
    <div class="space-y-1.5 p-6 flex flex-row items-center gap-4">
      <%= render partial: "project_spaces/form", locals: {
        project_space: @project_space,
        projects: @projects,
      } %>
    </div>
  </div>
</div>

app/views/project_spaces/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Project spaces</h1>

<div id="project_spaces">
  <% @project_spaces.each do |project_space| %>
    <%= render project_space %>
    <p>
      <%= link_to "Show this project space", project_space_path(project_space, project_space) %>
    </p>
  <% end %>
</div>

<%= link_to "New project space", new_project_space_path %>

app/views/project_spaces/new.html.erb
<div class="flex flex-col">
  <div class="rounded-lg border bg-white text-card-foreground shadow-sm">
    <div class="space-y-1.5 p-6 flex flex-row items-center gap-4">
      <div class="grid gap-1">
        <h3 class="text-2xl font-semibold leading-none tracking-tight">
          New Project Space
        </h3>
      </div>
    </div>
  </div>

  <div class="rounded-lg border bg-white text-card-foreground shadow-sm mt-4">
    <div class="space-y-1.5 p-6 flex flex-row items-center gap-4">
      <%= render partial: "project_spaces/form", locals: {
        project_space: @project_space,
        projects: @projects,
      } %>
    </div>
  </div>
</div>

app/views/project_spaces/show.html.erb
<div class="flex flex-col">
  <%= render partial: "shared/flash_message" %>

  <%= render @project_space %>

  <% @categories.each do |category| %>
  <%= render partial: "project_spaces/category_group", locals: { category: category, project_space: @project_space } %>
  <% end %>

  <% if @project_space.images.size > 0 %>
  <h4 class="text-xl font-semibold leading-none tracking-tight mt-8">
    Inspiration
  </h4>

  <div class="rounded border text-card-foreground bg-white shadow-sm mt-4">
    <div class="columns-3 md:columns-4 lg:columns-6 p-4">
      <% @project_space.images.each do |image| %>
      <img class="rounded-lg w-full h-full mb-4" src="<%= url_for(image) %>" />
      <% end %>
    </div>
  </div>
  <% end %>
</div>