config/routes.rb
Rails.application.routes.draw do
  resources :posts
  # Authentication
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [:index, :show, :destroy]
  resource  :password, only: [:edit, :update]
  namespace :identity do
    resource :email,              only: [:edit, :update]
    resource :email_verification, only: [:show, :create]
    resource :password_reset,     only: [:new, :edit, :create, :update]
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "projects#index"

  # Clients
  resources :clients

  # Comments
  resources :comments, only: [:create, :destroy]

  # Documents
  resources :documents

  # Invoices
  resources :invoices

  # Projects
  resources :projects do
    # Invoice
    resources :invoices

    # Spaces
    get "spaces/bulk_new", to: "project_spaces#bulk_new"
    post "spaces/bulk_create", to: "project_spaces#bulk_create"
    resources :spaces, controller: "project_spaces" do
      post :duplicate
      resources :items, controller: "project_items"
    end

    # Quotes
    resources :quotes
  end

  # Project Items
  resources :project_items, only: [:create, :destroy, :update] do
    post :duplicate
  end

  # Quotes
  resources :quotes

  # Users
  resources :users
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :organization

  has_many :clients_projects
  has_many :projects, through: :clients_projects
  has_many :clients_users
  has_many :users, through: :clients_users
end

app/models/clients_user.rb
class ClientsUser < ApplicationRecord
  belongs_to :client
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :record, polymorphic: true
  belongs_to :user

  validates :body, presence: true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  attribute :user_agent, :ip_address

  delegate :user, to: :session, allow_nil: true
end

app/models/document.rb
class Document < ApplicationRecord
  has_one_attached :original_document

  belongs_to :project
  belongs_to :user

  validates :title, presence: true
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  has_one_attached :original_document
  has_one_attached :remittance_document

  belongs_to :project
  belongs_to :quote, optional: true
  belongs_to :supplier
  belongs_to :user

  validates :due_date, :reference, :total, presence: true
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :clients

  has_many :organizations_projects
  has_many :projects, through: :organizations_projects
  
  has_many :organizations_users
  has_many :users, through: :organizations_users
end

app/models/post.rb
class Post < ApplicationRecord
  has_rich_text :content

  belongs_to :project
  belongs_to :user

  has_many :comments, as: :record, dependent: :destroy

  validates :title, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
  alias_attribute :items, :project_items
  alias_attribute :spaces, :project_spaces

  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize_to_limit: [500, 340]
  end

  belongs_to :parent_project, class_name: 'Project', optional: true

  has_many :clients_projects
  has_many :clients, through: :clients_projects
  has_many :documents
  has_many :invoices
  has_many :organizations_projects
  has_many :organizations, through: :organizations_projects
  has_many :posts
  has_many :project_spaces, dependent: :destroy
  has_many :project_items, through: :project_spaces
  has_many :sub_projects, class_name: 'Project', foreign_key: 'parent_project_id'
  has_many :quotes

  scope :joins_parent_project, -> {
    joins('LEFT JOIN projects parent_projects ON projects.parent_project_id = parent_projects.id')
  }

  scope :joins_sub_projects, -> {
    joins('INNER JOIN projects sub_projects ON projects.id = sub_projects.parent_project_id')
  }

  def combined_clients_name
    if self.clients.size > 0
      return self.clients.map { |c| c.title }.join(" / ")
    end

    return "No Client"
  end

  def master_project
    return self.parent_project if !self.is_master
    return self
  end
end

app/models/project_item.rb
class ProjectItem < ApplicationRecord
  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
  end
  has_many :comments, as: :record

  belongs_to :category
  belongs_to :project
  belongs_to :project_space
  belongs_to :supplier, optional: true
  belongs_to :status, optional: true
  
  validates :title, presence: true

  before_create :set_default_attributes
  after_commit :add_changes_comment, on: :update

  private

    def set_default_attributes
      self.attributes = {
        status: self.status || Status.find_by(key: "draft"),
      }
    end

    def add_changes_comment
      if saved_changes?
        changes = saved_changes.except("updated_at", "created_at")

        changes_string = "#{Current.user.first_name} made the following changes:\n"
        changes_string = changes.keys.each_with_index.reduce(changes_string) do |acc, (key, index)|
          acc += "#{key}: #{changes[key][0]} => #{changes[key][1]}"
          acc += "\n" if index < changes.keys.length - 1
          acc
        end
        
        Comment.create(record: self, body: changes_string, user: Current.user)
      end
    end
end

class ProjectItemCloner < Clowne::Cloner
  finalize do |source, record, params|
    record.image.attach(source.image.blob) if source.image.attached?
  end

  trait :append_copy do
    finalize do |source, record, params|
      record.title = "#{source.title} Copy"
    end
  end
end

app/models/project_space.rb
class ProjectSpace < ApplicationRecord
  belongs_to :project

  has_many :project_items
  has_many_attached :images do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
  end
end

class ProjectSpaceCloner < Clowne::Cloner
  include_association :project_items

  trait :append_copy do
    finalize do |source, record, params|
      record.title = "#{source.title} Copy"
    end
  end
end

app/models/quote.rb
class Quote < ApplicationRecord
  has_one_attached :original_document
  has_one_attached :signed_document

  belongs_to :project
  belongs_to :supplier
  belongs_to :user

  validates :reference, :total, presence: true
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user

  before_create do
    self.user_agent = Current.user_agent
    self.ip_address = Current.ip_address
  end
end

app/models/status.rb
class Status < ApplicationRecord
end

app/models/supplier.rb
class Supplier < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  generates_token_for :email_verification, expires_in: 2.days do
    email
  end
  generates_token_for :password_reset, expires_in: 20.minutes do
    password_salt.last(10)
  end

  belongs_to :role
  
  has_many :clients_users
  has_many :clients, through: :clients_users
  has_many :organizations_users
  has_many :organizations, through: :organizations_users
  has_many :sessions, dependent: :destroy

  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, allow_nil: true, length: { minimum: 12 }

  normalizes :email, with: -> { _1.strip.downcase }

  before_validation if: :email_changed?, on: :update do
    self.verified = false
  end

  after_update if: :password_digest_previously_changed? do
    sessions.where.not(id: Current.session).delete_all
  end

  def admin?
    self.role&.key == 'admin'
  end

  def client_user?
    self.role&.key == 'client_user'
  end

  def organization_user?
    self.role&.key == 'organization_user'
  end

  def full_name
    if self.first_name.present?
      return "#{self.first_name} #{self.last_name}"
    end

    return "No Name Set"
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/shared/_flash_message.html.erb
<% if notice.present? || alert.present? %>
<div class="mb-4 bg-teal-100 border-t-4 border-teal-500 rounded-b text-teal-900 px-4 py-3 shadow" role="alert">
  <div class="flex items-center">
    <div class="py-1"><svg class="fill-current h-6 w-6 text-teal-500 mr-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M2.93 17.07A10 10 0 1 1 17.07 2.93 10 10 0 0 1 2.93 17.07zm12.73-1.41A8 8 0 1 0 4.34 4.34a8 8 0 0 0 11.32 11.32zM9 11V9h2v6H9v-4zm0-6h2v2H9V5z"/></svg></div>
    <div>
      <p class="font-bold"><%= notice || alert %></p>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_header.html.erb
<header class="flex items-center justify-between h-16 px-4 border-b shrink-0 md:px-6">
  <nav class="font-medium flex flex-row items-center gap-4 md:gap-5 text-sm lg:gap-6">
    <% if Current.user %>
    <a class="text-black dark:text-gray-400" href="<%= projects_path %>">
      Projects
    </a>
      <% if Current.user.organization_user? %>
      <a class="text-black dark:text-gray-400" href="<%= clients_path %>">
        Clients
      </a>
      <a class="text-black dark:text-gray-400" href="<%= users_path %>">
        Team
      </a>
      <% end %>
    <% end %>
  </nav>

  <% if Current.user %>
  <div class="flex items-center w-auto gap-2">
    <div class="flex items-center ml-auto">
      <div class="flex flex-col items-end text-sm mr-4">
        <span class="font-medium"><%= Current.user.full_name %></span>
        <%= button_to "Sign Out", Current.session, method: :delete, class: "text-sm", form_class: "inline-flex" %>
      </div>

      <a href="<%= edit_user_path(Current.user) %>" class="border inline-flex items-center justify-center text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 hover:bg-accent hover:text-accent-foreground h-10 w-10 rounded-full">
        <%= Current.user.email.first.upcase %>
      </a>
    </div>
  </div>
  <% end %>
</header>

app/views/statuses/_status_pill.html.erb
<%
  status_colours = {
    "approved" => {
      "background" => "rgb(36, 161, 72)",
      "border" => "rgb(36, 161, 72)",
      "text" => "#ffffff",
    },
    "draft" => {
      "background" => "#ffffff",
      "border" => "#2dd4bf",
      "text" => "#2dd4bf",
    },
    "in_review" => {
      "background" => "#ffffff",
      "border" => "#fda4af",
      "text" => "#fda4af",
    },
    "shortlist" => {
      "background" => "#ffffff",
      "border" => "#93c5fd",
      "text" => "#93c5fd",
    },
  }
%>

<div
  class="border border-[--status-border-color] bg-[--status-bg-color] text-[--status-text-color] text-center rounded-lg px-3 py-1"
  style="
    --status-bg-color: <%= status_colours[status&.key || "draft"]["background"] %>;
    --status-border-color: <%= status_colours[status&.key || "draft"]["border"] %>;
    --status-text-color: <%= status_colours[status&.key || "draft"]["text"] %>;
  "
>
  <%= status&.title || "Draft" %>
</div>