config/routes.rb
Rails.application.routes.draw do
  resources :posts
  # Authentication
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [:index, :show, :destroy]
  resource  :password, only: [:edit, :update]
  namespace :identity do
    resource :email,              only: [:edit, :update]
    resource :email_verification, only: [:show, :create]
    resource :password_reset,     only: [:new, :edit, :create, :update]
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "projects#index"

  # Clients
  resources :clients

  # Comments
  resources :comments, only: [:create, :destroy]

  # Documents
  resources :documents

  # Invoices
  resources :invoices

  # Projects
  resources :projects do
    # Invoice
    resources :invoices

    # Spaces
    get "spaces/bulk_new", to: "project_spaces#bulk_new"
    post "spaces/bulk_create", to: "project_spaces#bulk_create"
    resources :spaces, controller: "project_spaces" do
      post :duplicate
      resources :items, controller: "project_items"
    end

    # Quotes
    resources :quotes
  end

  # Project Items
  resources :project_items, only: [:create, :destroy, :update] do
    post :duplicate
  end

  # Quotes
  resources :quotes

  # Users
  resources :users
end

app/models/document.rb
class Document < ApplicationRecord
  has_one_attached :original_document

  belongs_to :project
  belongs_to :user

  validates :title, presence: true
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: %i[ show edit update destroy ]

  # GET /documents or /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1 or /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
    @document.project_id = params[:project_id]
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents or /documents.json
  def create
    @document = Document.new(document_params)
    @document.user = current_user

    respond_to do |format|
      if @document.save
        format.html { redirect_to project_url(@document.project_id), notice: "Document was successfully created." }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1 or /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to document_url(@document), notice: "Document was successfully updated." }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1 or /documents/1.json
  def destroy
    @document.destroy!

    respond_to do |format|
      format.html { redirect_to documents_url, notice: "Document was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def document_params
      params.fetch(:document, {})
        .permit(
          :original_document,
          :project_id,
          :title,
        )
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_document.html.erb
<div id="<%= dom_id document %>">
</div>

app/views/documents/_form.html.erb
<%= form_with(model: document, class: "w-full") do |form| %>
  <% if document.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
        <% document.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex flex-wrap -mx-3 mb-2">
    <div class="w-full px-3">
      <%= form.label "Title", class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
      <%= form.text_field :title, class: "appearance-none block w-full bg-gray-50 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" %>
    </div>
  </div>

  <div class="flex flex-wrap -mx-3 mb-2">
    <div class="w-full px-3 mb-2 md:mb-0">
      <%= form.label "Original Document", class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
      <%= form.file_field :original_document, class: "appearance-none block w-full bg-gray-50 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" %>
    </div>
  </div>

  <div class="flex justify-end pt-4 border-t">
    <%= form.hidden_field :project_id, value: document.project_id || params[:project_id] %>

    <%= link_to "Go Back", project_path(document.project_id), class: "cursor-pointer inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border text-primary h-10 px-4 py-2 mr-2" %>
    <%= form.submit class: "cursor-pointer inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground hover:bg-primary/90 h-10 px-4 py-2" %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<div class="flex flex-col">
  <div class="rounded-lg border bg-white text-card-foreground shadow-sm">
    <div class="space-y-1.5 p-6 flex flex-row items-center gap-4">
      <div class="grid gap-1">
        <h3 class="text-2xl font-semibold leading-none tracking-tight">
          Edit Document
        </h3>
      </div>
    </div>
  </div>

  <div class="rounded-lg border bg-white text-card-foreground shadow-sm mt-4">
    <div class="space-y-1.5 p-6 flex flex-row items-center gap-4">
      <%= render partial: "documents/form", locals: {
        document: @document,
      } %>
    </div>
  </div>
</div>

app/views/documents/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Documents</h1>

<div id="documents">
  <% @documents.each do |document| %>
    <%= render document %>
    <p>
      <%= link_to "Show this document", document %>
    </p>
  <% end %>
</div>

<%= link_to "New document", new_document_path %>

app/views/documents/new.html.erb
<div class="flex flex-col">
  <div class="rounded-lg border bg-white text-card-foreground shadow-sm">
    <div class="space-y-1.5 p-6 flex flex-row items-center gap-4">
      <div class="grid gap-1">
        <h3 class="text-2xl font-semibold leading-none tracking-tight">
          Add Document
        </h3>
      </div>
    </div>
  </div>

  <div class="rounded-lg border bg-white text-card-foreground shadow-sm mt-4">
    <div class="space-y-1.5 p-6 flex flex-row items-center gap-4">
      <%= render partial: "documents/form", locals: {
        document: @document,
      } %>
    </div>
  </div>
</div>

app/views/documents/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @document %>

<div>
  <%= link_to "Edit this document", edit_document_path(@document) %> |
  <%= link_to "Back to documents", documents_path %>

  <%= button_to "Destroy this document", @document, method: :delete %>
</div>