config/routes.rb
Rails.application.routes.draw do
  resources :posts
  # Authentication
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [:index, :show, :destroy]
  resource  :password, only: [:edit, :update]
  namespace :identity do
    resource :email,              only: [:edit, :update]
    resource :email_verification, only: [:show, :create]
    resource :password_reset,     only: [:new, :edit, :create, :update]
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "projects#index"

  # Clients
  resources :clients

  # Comments
  resources :comments, only: [:create, :destroy]

  # Documents
  resources :documents

  # Invoices
  resources :invoices

  # Projects
  resources :projects do
    # Invoice
    resources :invoices

    # Spaces
    get "spaces/bulk_new", to: "project_spaces#bulk_new"
    post "spaces/bulk_create", to: "project_spaces#bulk_create"
    resources :spaces, controller: "project_spaces" do
      post :duplicate
      resources :items, controller: "project_items"
    end

    # Quotes
    resources :quotes
  end

  # Project Items
  resources :project_items, only: [:create, :destroy, :update] do
    post :duplicate
  end

  # Quotes
  resources :quotes

  # Users
  resources :users
end

app/models/project.rb
class Project < ApplicationRecord
  alias_attribute :items, :project_items
  alias_attribute :spaces, :project_spaces

  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize_to_limit: [500, 340]
  end

  belongs_to :parent_project, class_name: 'Project', optional: true

  has_many :clients_projects
  has_many :clients, through: :clients_projects
  has_many :documents
  has_many :invoices
  has_many :organizations_projects
  has_many :organizations, through: :organizations_projects
  has_many :posts
  has_many :project_spaces, dependent: :destroy
  has_many :project_items, through: :project_spaces
  has_many :sub_projects, class_name: 'Project', foreign_key: 'parent_project_id'
  has_many :quotes

  scope :joins_parent_project, -> {
    joins('LEFT JOIN projects parent_projects ON projects.parent_project_id = parent_projects.id')
  }

  scope :joins_sub_projects, -> {
    joins('INNER JOIN projects sub_projects ON projects.id = sub_projects.parent_project_id')
  }

  def combined_clients_name
    if self.clients.size > 0
      return self.clients.map { |c| c.title }.join(" / ")
    end

    return "No Client"
  end

  def master_project
    return self.parent_project if !self.is_master
    return self
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = policy_scope(Project)
      .where(is_master: true)
  end

  # GET /projects/1 or /projects/1.json
  def show
    authorize @project
  end

  # GET /projects/new
  def new
    @project = Project.new
    @project.client_ids << params[:client_id] if params[:client_id]
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)
    
    result = Projects::SetupNewProject.new({
      current_user: current_user,
      project: @project,
    }).perform

    if !result[:success]
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: result[:errors], status: :unprocessable_entity }
      end
      return
    end

    @project = result[:data]
    authorize @project

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy!

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.fetch(:project, {})
        .permit(
          :budget,
          :image,
          :is_master,
          :parent_project_id,
          :title,
          :client_ids => [],
        )
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, class: "w-full", data: { controller: "project-items--form" }) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex flex-wrap -mx-3 mb-2">
    <div class="w-full px-3">
      <%= form.label "Title", class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
      <%= form.text_field :title, class: "appearance-none block w-full bg-gray-50 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" %>
    </div>
  </div>

  <div class="flex flex-wrap -mx-3 mb-2">
    <div class="w-full px-3">
      <%= form.label "Budget", class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
      <%= form.number_field :budget, class: "appearance-none block w-full bg-gray-50 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" %>
    </div>
  </div>

  <% if ((project.new_record? && !params[:parent_project_id].present?) || project.is_master) && clients.size > 0 %>
    <div class="w-full px-3 flex flex-col gap-1">
      <%= form.label "Clients", class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
      <%= form.collection_check_boxes :client_ids, clients, :id, :title do |b| %>
        <span class="flex items-center gap-2">
          <%= b.check_box(class: "w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600") %>
          <%= b.label %>
        </span>
      <% end %>
    </div>
    <% end %>

  <div class="flex flex-wrap -mx-3 mb-2">
    <div class="w-full px-3">
      <%= form.label "Image", class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
      <%= form.file_field :image, class: "appearance-none block w-full bg-gray-50 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" %>
    </div>
  </div>

  <div class="flex justify-end">
    <%= form.hidden_field :is_master, value: !params[:parent_project_id].present? %>
    <%= form.hidden_field :parent_project_id, value: params[:parent_project_id] %>

    <% if project.new_record? && params[:parent_project_id].present? %>
    <%= link_to "Go Back", project_path(params[:parent_project_id]), class: "cursor-pointer inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border text-primary h-10 px-4 py-2 mr-2" %>
    <% elsif project.new_record? %>
    <%= link_to "Go Back", projects_path, class: "cursor-pointer inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border text-primary h-10 px-4 py-2 mr-2" %>
    <% else %>
    <%= link_to "Go Back", project_path(project), class: "cursor-pointer inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border text-primary h-10 px-4 py-2 mr-2" %>
    <% end %>
    <%= form.submit class: "cursor-pointer inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground hover:bg-primary/90 h-10 px-4 py-2" %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>" class="rounded-lg border bg-white text-card-foreground shadow-sm">
  <div class="w-full h-64 border-b bg-gray-50 rounded-t-lg">
    <%= link_to(project) do %>
      <% if project.image.attached? %>
      <%= image_tag(project.image, class: "object-bottom object-cover h-full w-full rounded-t-lg") %>
      <% else %>
      <%= image_tag("project_placeholder.png", class: "object-bottom object-cover h-full w-full rounded-t-lg") %>
      <% end %>
    <% end %>
  </div>

  <div class="space-y-1.5 p-4 flex flex-row items-center">
    <div class="grid gap-1">
      <h3 class="text-lg font-semibold leading-none tracking-tight">
        <%= link_to project.title, project %>
      </h3>
      
      <h4 class="text-sm">
        <% if project.is_master %>
          <%= project.combined_clients_name %>
        <% else %>
          <%= link_to project.parent_project.title, project.parent_project %>
        <% end %>
      </h4>
    </div>
  </div>
</div>

app/views/projects/_project_clients.html.erb
<div class="rounded-lg border bg-white text-card-foreground shadow-sm mt-4">
  <div class="space-y-1.5 p-6 flex flex-col gap-4">
    <div class="flex justify-between">
      <h3 class="text-2xl font-semibold leading-none tracking-tight">
        Clients
      </h3>

      <div class="flex items-center text-sm gap-2">
        <%= link_to "Add Client", new_client_path(project_id: project.id, redirect: project_path(project)), class: "cursor-pointer inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border text-primary h-7 px-2 py-1" %>
        <%= link_to "Assign Clients", edit_project_path(project), class: "cursor-pointer inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground hover:bg-primary/90 h-7 px-2 py-1" %>
      </div>
    </div>

    <% if project.clients.size > 0 %>
    <div class="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
      <% project.clients.each do |client| %>
      <%= render partial: "clients/client_tile", locals: { client: client } %>
      <% end %>
    </div>
    <% end %>
  </div>
</div>

app/views/projects/_project_documents.html.erb
<div class="rounded-lg border bg-white text-card-foreground shadow-sm mt-4">
  <div class="space-y-1.5 p-6 flex flex-col gap-4">
    <div class="flex justify-between">
      <h3 class="text-2xl font-semibold leading-none tracking-tight">
        Documents
      </h3>

      <div class="flex items-center text-sm gap-4">
        <%= link_to "Add Document", new_document_path(project_id: project.id), class: "cursor-pointer inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground hover:bg-primary/90 h-7 px-2 py-1" %>
      </div>
    </div>

    <% if project.documents.size > 0 %>
    <div class="relative w-full overflow-auto">
      <table class="w-full caption-bottom text-sm">
        <thead class="[&amp;_tr]:border-b">
          <tr class="border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted">
            <th class="h-12 px-4 text-left align-middle font-medium text-muted-foreground w-[300px]">
              Title
            </th>
          </tr>
        </thead>
        <tbody class="[&amp;_tr:last-child]:border-0">
          <% project.documents.order(created_at: :desc).each do |document| %>
          <tr class="border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted">
            <td class="p-4 align-middle font-medium">
              <%= link_to document.title, rails_blob_path(document.original_document, disposition: "attachment") %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <% end %>
  </div>
</div>

app/views/projects/_project_invoices.html.erb
<div class="rounded-lg border bg-white text-card-foreground shadow-sm mt-4">
  <div class="space-y-1.5 p-6 flex flex-col gap-4">
    <div class="flex justify-between">
      <h3 class="text-2xl font-semibold leading-none tracking-tight">
        Invoices
      </h3>

      <div class="flex items-center text-sm gap-4">
        <%= link_to "Add Invoice", new_project_invoice_path(project), class: "cursor-pointer inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground hover:bg-primary/90 h-7 px-2 py-1" %>
      </div>
    </div>

    <% if project.invoices.size > 0 %>
    <div class="relative w-full overflow-auto">
      <table class="w-full caption-bottom text-sm">
        <thead class="[&amp;_tr]:border-b">
          <tr class="border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted">
            <th class="h-12 px-4 text-left align-middle font-medium text-muted-foreground [&amp;:has([role=checkbox])]:pr-0 w-[300px]">
              Reference
            </th>
            <th class="h-12 px-4 text-left align-middle font-medium text-muted-foreground [&amp;:has([role=checkbox])]:pr-0">
              Supplier
            </th>
            <th class="h-12 px-4 text-left align-middle font-medium text-muted-foreground [&amp;:has([role=checkbox])]:pr-0">
              Description
            </th>
            <th class="h-12 px-4 align-middle font-medium text-muted-foreground [&amp;:has([role=checkbox])]:pr-0 text-right">
              Amount
            </th>
          </tr>
        </thead>
        <tbody class="[&amp;_tr:last-child]:border-0">
          <% project.invoices.each do |invoice| %>
          <tr class="border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted">
            <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0 font-medium">
              <%= link_to invoice.reference, edit_invoice_path(invoice) %>
            </td>
            <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0">
              <%= invoice.supplier&.title %>
            </td>
            <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0">
              <%= invoice.description %>
            </td>
            <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0 text-right">
              <%= number_to_currency(invoice.total) %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="self-end">
      <span class="font-bold">Total:</span> <%= number_to_currency(project.invoices.sum(:total)) %>
    </div>
    <% end %>
  </div>
</div>

app/views/projects/_project_mood_board.html.erb
<div class="flex flex-col">
  <%= render partial: "shared/flash_message" %>

  <div class="rounded-lg border bg-white text-card-foreground shadow-sm">
    <div class="p-6 flex flex-col gap-2 md:gap-0 md:flex-row md:items-center justify-between">
      <div class="flex flex-col gap-2">
        <h3 class="text-2xl font-semibold leading-none tracking-tight">
          <%= link_to @project.title, @project %>
        </h3>
        
        <h4>
          <% if @project.is_master %>
            <%= @project.combined_clients_name %>
          <% else %>
            <%= link_to @project.parent_project.title, @project.parent_project %>
          <% end %>
        </h4>
      </div>
      
      <div>
        <%= link_to "Go Back", project_path(@project), class: "inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 text-primary border hover:border-gray-300 h-10 px-4 py-2" %>
      </div>
    </div>
  </div>

  <%= render partial: "projects/mood_board/board", locals: {
    project: @project,
  } %>
</div>

app/views/projects/_project_posts.html.erb
<div class="rounded-lg border bg-white text-card-foreground shadow-sm mt-4">
  <div class="space-y-1.5 p-6 flex flex-col gap-4">
    <div class="flex justify-between">
      <h3 class="text-2xl font-semibold leading-none tracking-tight">
        Posts
      </h3>

      <div class="flex items-center text-sm gap-4">
        <%= link_to "Add Post", new_post_path(project_id: project.id), class: "cursor-pointer inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground hover:bg-primary/90 h-7 px-2 py-1" %>
      </div>
    </div>

    <% if project.posts.size > 0 %>
    <div class="relative w-full overflow-auto">
      <table class="w-full caption-bottom text-sm">
        <thead class="[&amp;_tr]:border-b">
          <tr class="border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted">
            <th class="h-12 px-4 text-left align-middle font-medium text-muted-foreground">
              Title
            </th>
            <th class="h-12 px-4 text-right align-middle font-medium text-muted-foreground">
              Comments
            </th>
          </tr>
        </thead>
        <tbody class="[&amp;_tr:last-child]:border-0">
          <% project.posts.order(created_at: :desc).each do |post| %>
          <tr class="border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted">
            <td class="p-4 align-middle font-medium">
              <%= link_to post.title, post_path(post) %>
            </td>
            <td class="p-4 align-middle text-right">
              <%= pluralize(post.comments.count, "Comment") %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <% end %>
  </div>
</div>

app/views/projects/_project_quotes.html.erb
<div class="rounded-lg border bg-white text-card-foreground shadow-sm mt-4">
  <div class="space-y-1.5 p-6 flex flex-col gap-4">
    <div class="flex justify-between">
      <h3 class="text-2xl font-semibold leading-none tracking-tight">
        Quotes
      </h3>

      <div class="flex items-center text-sm gap-4">
        <%= link_to "Add Quote", new_project_quote_path(project), class: "cursor-pointer inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground hover:bg-primary/90 h-7 px-2 py-1" %>
      </div>
    </div>

    <% if project.quotes.size > 0 %>
    <div class="relative w-full overflow-auto">
      <table class="w-full caption-bottom text-sm">
        <thead class="[&amp;_tr]:border-b">
          <tr class="border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted">
            <th class="h-12 px-4 text-left align-middle font-medium text-muted-foreground [&amp;:has([role=checkbox])]:pr-0 w-[300px]">
              Reference
            </th>
            <th class="h-12 px-4 text-left align-middle font-medium text-muted-foreground [&amp;:has([role=checkbox])]:pr-0">
              Supplier
            </th>
            <th class="h-12 px-4 text-left align-middle font-medium text-muted-foreground [&amp;:has([role=checkbox])]:pr-0">
              Description
            </th>
            <th class="h-12 px-4 align-middle font-medium text-muted-foreground [&amp;:has([role=checkbox])]:pr-0 text-right">
              Amount
            </th>
          </tr>
        </thead>
        <tbody class="[&amp;_tr:last-child]:border-0">
          <% project.quotes.each do |quote| %>
          <tr class="border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted">
            <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0 font-medium">
              <%= link_to quote.reference, edit_quote_path(quote) %>
            </td>
            <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0">
              <%= quote.supplier&.title %>
            </td>
            <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0">
              <%= quote.description %>
            </td>
            <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0 text-right">
              <%= number_to_currency(quote.total) %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="self-end">
      <span class="font-bold">Total:</span> <%= number_to_currency(project.quotes.sum(:total)) %>
    </div>
    <% end %>
  </div>
</div>

app/views/projects/_project_spaces.html.erb
<div class="rounded-lg border bg-white text-card-foreground shadow-sm mt-4">
  <div class="space-y-1.5 p-6 flex flex-col gap-4">
    <div class="flex justify-between">
      <h3 class="text-2xl font-semibold leading-none tracking-tight">
        Spaces
      </h3>

      <div class="flex items-center text-sm gap-4">
        <%= link_to "Add Space", new_project_space_path(project), class: "cursor-pointer inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground hover:bg-primary/90 h-7 px-2 py-1" %>
      </div>
    </div>

    <% if project.spaces.size > 0 %>
    <div class="relative w-full overflow-auto">
      <table class="w-full caption-bottom text-sm">
        <thead class="[&amp;_tr]:border-b">
          <tr class="border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted">
            <th class="h-12 px-4 text-left align-middle font-medium text-muted-foreground w-[300px]">
              Title
            </th>
            <th class="h-12 px-4 align-middle font-medium text-muted-foreground text-right">
              Item Count
            </th>
          </tr>
        </thead>
        <tbody class="[&amp;_tr:last-child]:border-0">
          <% project.spaces.order(title: :asc).each do |project_space| %>
          <tr class="border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted">
            <td class="p-4 align-middle font-medium">
              <%= link_to project_space.title, project_space_path(project, project_space) %>
            </td>
            <td class="p-4 align-middle text-right">
              <%= pluralize(project_space.project_items.count, "item") %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="self-end">
      <span class="font-bold">Total:</span> <%= number_to_currency(project.invoices.sum(:total)) %>
    </div>
    <% end %>
  </div>
</div>

app/views/projects/_project_table.html.erb
<div class="flex flex-col">
  <%= render partial: "shared/flash_message" %>

  <div class="rounded-lg border bg-white text-card-foreground shadow-sm">
    <div class="p-6 flex flex-col gap-2 md:gap-0 md:flex-row md:items-center justify-between">
      <div class="flex flex-col gap-2">
        <h3 class="text-2xl font-semibold leading-none tracking-tight">
          <%= link_to @project.title, @project %>
        </h3>
        
        <h4>
          <% if @project.is_master %>
            <%= @project.combined_clients_name %>
          <% else %>
            <%= link_to @project.parent_project.title, @project.parent_project %>
          <% end %>
        </h4>
      </div>
      
      <div>
        <%= link_to "Go Back", project_path(@project), class: "inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 text-primary border hover:border-gray-300 h-10 px-4 py-2" %>
      </div>
    </div>
  </div>

  <%= render partial: "projects/table_view/table", locals: {
    categories: Category.where(category_type: "ProjectItem"),
    project: @project,
  } %>
</div>

app/views/projects/edit.html.erb
<div class="flex flex-col">
  <div class="rounded-lg border bg-white text-card-foreground shadow-sm">
    <div class="space-y-1.5 p-6 flex flex-row items-center gap-4">
      <div class="grid gap-1">
        <h3 class="text-2xl font-semibold leading-none tracking-tight">
          Edit Project
        </h3>
      </div>
    </div>
  </div>

  <div class="rounded-lg border bg-white text-card-foreground shadow-sm mt-4">
    <div class="space-y-1.5 p-6 flex flex-row items-center gap-4">
      <%= render partial: "projects/form", locals: {
        clients: policy_scope(Client),
        project: @project,
      } %>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<div class="flex flex-col gap-4">
  <%= render partial: "shared/flash_message" %>

  <div class="rounded-lg border bg-white text-card-foreground shadow-sm">
    <div class="space-y-1.5 p-6 flex flex-row justify-between items-center gap-4">
      <h3 class="text-2xl font-semibold leading-none tracking-tight">
        Projects
      </h3>

      <% if Current.user.organization_user? %>
      <div class="flex items-center text-sm gap-4">
        <%= link_to "Add Project", new_project_path, class: "cursor-pointer inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground hover:bg-primary/90 h-7 px-2 py-1" %>
      </div>
      <% end %>
    </div>
  </div>

  <div id="projects" class="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
    <% @projects.order(updated_at: :asc).each do |project| %>
      <%= render project %>
    <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<div class="flex flex-col">
  <div class="rounded-lg border bg-white text-card-foreground shadow-sm">
    <div class="space-y-1.5 p-6 flex flex-row items-center gap-4">
      <div class="grid gap-1">
        <h3 class="text-2xl font-semibold leading-none tracking-tight">
          New Project
        </h3>
      </div>
    </div>
  </div>

  <div class="rounded-lg border bg-white text-card-foreground shadow-sm mt-4">
    <div class="space-y-1.5 p-6 flex flex-row items-center gap-4">
      <%= render partial: "projects/form", locals: {
        clients: policy_scope(Client),
        project: @project,
      } %>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<% if params[:mood_board] == "true" %>
<% return render partial: "projects/project_mood_board" %>
<% end %>

<% if params[:table_view] == "true" %>
<% return render partial: "projects/project_table" %>
<% end %>

<% if @project.is_master %>
<% return render partial: "projects/master_project" %>
<% end %>

<%= render partial: "projects/sub_project" %>